---
## This playbook deploys a Spring boot application

# Apply common configuration to all hosts
- hosts: target-server
  become: yes
  become_method: sudo

  tasks:

    - name: Stop gs-rest-service
      systemd:
        name: gs-rest-service
        state: stopped

    - copy:
        src: gs-rest-service-1.0.jar
        dest: /opt/gs-rest-service/current/gs-rest-service-1.0.jar
        mode: '0700'

    - name: Start gs-rest-service
      systemd:
        name: gs-rest-service
        state: started
