# Apply common configuration to all hosts
- hosts: target-server
  become: yes
  become_method: sudo

  tasks:

    - name: Disable Apache http if present
      yum:
        name: httpd
        state: absent


    - name: Install epel-release if not present
      yum: 
        name: epel-release
        state: latest

    - name: Install packages maven, java
      yum:
        name:
          - java-1.8.0-openjdk-devel
          - maven  
          - git 
        state: present

    # Example read-write git checkout from github
    - git:
        repo: https://github.com/PedroAndrade89/spring-rest.git
        dest: /root/spring-rest

        

    - name: Create symbolic link from spring app conf file
      file:
        src: /root/spring-rest/gs-rest
        dest: /etc/default/gs-rest
        state: link
        force: yes

    - name: Create symbolic link from spring app jar file
      file:
        src: /root/spring-rest/target/gs-rest-service-1.0.jar
        dest: /opt/gs-rest-service/current/gs-rest-service-1.0.jar
        state: link
        force: yes

    - name: Create systemd  
      file:
        src: /root/spring-rest/gs-rest.service
        dest: /etc/systemd/system/gs-rest.service
        state: link
        force: yes

    - name: Start gs-rest service
      systemd: 
        name: gs-rest
        state: started